### PR TITLE
Add detailed comments to each function.

### PR DESCRIPTION
**Pull request by NekoSakuraLucia**
- [x] Add comments to the following files: 
  - `useClipboard`
  - `useHover`
  - `useInViewport`
  - `useLocalStorage`
  - `useQueue`
  - `useMediaQuery`
  - `useScroll`
  - `useWindowScroll`

### CODE REVIEW

**Comment by NekoSakuraLucia** [comment]
@mhdcodes

**Review by mhdcodes — APPROVED** [review]

**Comment by mhdcodes** [comment]
Hey @NekoSakuraLucia thank you for this great PR, I will merge it right after you add the changesets.

**Comment by NekoSakuraLucia** [comment]
I've added the changeset already. Please check and review the code again, bro.

**Comment by NekoSakuraLucia** [comment]
> Hey @NekoSakuraLucia thank you for this great PR, I will merge it right after you add the changesets.

I've added the changeset already. Please check and review the code again, bro.

**Review by mhdcodes — APPROVED** [review]

**Pull request merged**
